# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\gt\Register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1028)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(190, 0, 1730, 1030))
        self.label_4.setStyleSheet("border-image: url(:/images/images/background.jpg);\n"
"border-top-right-radius:100px;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.widget_4 = QtWidgets.QWidget(Dialog)
        self.widget_4.setGeometry(QtCore.QRect(790, 350, 631, 521))
        self.widget_4.setObjectName("widget_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 45, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 164, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        self.label_6.setGeometry(QtCore.QRect(50, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("font: bold 14pt \"Times New Roman\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setGeometry(QtCore.QRect(50, 129, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("font: bold 14pt \"Times New Roman\";")
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 383, 521, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"font: bold 18pt \"Times New Roman\";\n"
"    background-color: rgb(33, 159, 255);  /* 微软蓝 */\n"
"    color: white;\n"
"    border: none;              /* 去除默认边框 */\n"
"    padding: 8px 16px;         /* 内边距 */\n"
"    border-radius: 8px;        /* 圆角 */\n"
"   \n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background-color: #006CBB;\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"    background-color: #005A9E;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.commandLinkButton_2 = QtWidgets.QCommandLinkButton(self.widget_4)
        self.commandLinkButton_2.setGeometry(QtCore.QRect(200, 460, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.commandLinkButton_2.setFont(font)
        self.commandLinkButton_2.setObjectName("commandLinkButton_2")
        self.label_8 = QtWidgets.QLabel(self.widget_4)
        self.label_8.setGeometry(QtCore.QRect(50, 248, 281, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("font: bold 14pt \"Times New Roman\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 283, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 190, 80))
        self.pushButton_4.setStyleSheet("border-image: url(:/images/images/MTR.png);\n"
"background-color: rgb(145, 145, 145);\n"
"border-radius:100px;")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(360, 20, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: bold 24pt \"Times New Roman\";\n"
"color: rgb(16, 74, 200);")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 80, 190, 950))
        self.frame.setStyleSheet("background-color: rgb(190, 199, 211);\n"
"QPushButton{\n"
"border:none;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(162, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_28.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_28.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_6.addWidget(self.pushButton_28)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 160))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_9.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_7.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_8.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_11.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_4.addWidget(self.pushButton_11, 0, QtCore.Qt.AlignLeft)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_14.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_5.addWidget(self.pushButton_14, 0, QtCore.Qt.AlignLeft)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_15.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_15.setStyleSheet("\n"
"QPushButton {\n"
"border:none;\n"
"font: bold 10pt \"Times New Roman\";\n"
"}\n"
"\n"
"/* 鼠标悬停效果 */\n"
"QPushButton:hover {\n"
"    background: #5B7C9A;\n"
"\n"
"}\n"
"\n"
"/* 按下效果 */\n"
"QPushButton:pressed {\n"
"   background: #4B6C8A;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.verticalLayout_5.addWidget(self.pushButton_15, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.frame_7)
        self.frame_12 = QtWidgets.QFrame(self.frame)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout.addWidget(self.frame_10)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Enter your user name:you@example.com"))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Enter your password"))
        self.label_6.setText(_translate("Dialog", "Username"))
        self.label_7.setText(_translate("Dialog", "Password"))
        self.pushButton_3.setText(_translate("Dialog", "Register"))
        self.commandLinkButton_2.setText(_translate("Dialog", "Return to Log in"))
        self.label_8.setText(_translate("Dialog", "Confirm Your Password"))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "Enter your password again"))
        self.label_2.setText(_translate("Dialog", "Eyes-T Register"))
        self.pushButton_28.setText(_translate("Dialog", "Alarm Window"))
        self.pushButton_9.setText(_translate("Dialog", "DAL"))
        self.pushButton_7.setText(_translate("Dialog", "Point"))
        self.pushButton_8.setText(_translate("Dialog", "Train"))
        self.pushButton_10.setText(_translate("Dialog", "Power"))
        self.pushButton_11.setText(_translate("Dialog", "Point Analysis              "))
        self.pushButton_12.setText(_translate("Dialog", "Train SPAD Detection"))
        self.pushButton_14.setText(_translate("Dialog", "Setting                           "))
        self.pushButton_15.setText(_translate("Dialog", "Logout                           "))
import resource_rc
